-- INSERT INTO VALUES

-- NTS
-- SQL = NULL
-- PYTHON = NONE

-- items (name, gift)
-- locations (name, plot, c1, c2, c3, m1, m2, m3, cost, enc, item)
-- INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, enc, item, img) VALUES ();
-- players (email, password_hash, name)
-- specials (sp_name, sp_atk, mp_val) - NOT CURRENT
-- classes (hero_class, hero_atk, hero_hp, hero_mp, item)
-- encounters (enc_type, enc_atk, enc_hp)
-- heroes (hero_id, hero_class, hero_atk, hero_hp, hero_mp, location_id)

INSERT INTO items (item_name, gift) VALUES ('FLASK potion', 50); -- heals 50 points of any
INSERT INTO items (item_name, gift) VALUES ('Java Script', 20); -- heals 20 points of any
INSERT INTO items (item_name, gift) VALUES ('Cascading Time Script', 0); -- allows you turn reverse time 
INSERT INTO items (item_name, gift) VALUES ('SQLiser', 25); -- buffs ATK by 25 points
INSERT INTO items (item_name, gift) VALUES ('Python', 30); -- buffs ATK by 35 points
INSERT INTO items (item_name, gift) VALUES ('Hyper Potion - Alien Language', 50); -- heals 50 points of all

INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES ('a darkly lit cavern','You awaken to find yourself in a darkly lit cavern and when your eyes adjust, you notice a door.','Head for the door','Examine your surroundings',NULL,22,28,NULL,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('you win','Under development.');
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES(E'knight\’s trial',E'As you approach the knight, it raises it\’s halberd towards you. At the end of pike head, an image materialises. \‘NAME!\’, it demands. You don\’t know what it means.',E'\‘NAME!\’','Stay silent',E'\‘{{ hero[2] }}\’',27,36,64,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('shadowlight streets','Under development.'),('you died','Under development.');
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('certain poison',E'You confidently head down the path surrounded by bushes. After a moment, the bushes oddly change in colour and become a bright blue. A mist starts to spray out of the blue bushes and you can\’t help but breathe in the fumes.','Hold your breath',NULL,NULL,44,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('you died',E'Dark shadows don\’t scare me! You stand tall and decide to walk calmly past whatever these dark structures may be. Unfortunately, the appear to be deathly horseman. When you finally notice, you find your feet are tethered to the ground by some smokey haze, only to look up and be impaled in the chest by a black-silver lance.','GAME','OVER','You lose.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('unknown forest','Under development.');
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('you died',E'You motion to grab your weapon but your arm freezes. As you down, you behold a mind-melting sight - you arm begins to dematerialise into some black cubic smoke. The disintegration travels up to your arm and into your shoulder. You don\’t feel any pain. The creature starts to stretch towards your face and you feel your mouth being forced open. Then you feel no more.','GAME','OVER','You lose.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('you died','Under development.');

INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('Victorian castleside','The samurai like your answer and separate to let you pass. As you pass them by, they once again cobble together to the block the path. Looking ahead you see a library amongst the buildings, as well as a diverging nature path.','Path to the library','Path through the bushes','Path through the boulders',40,6,43,NULL,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('castle riverside',E'As you plunge into the cold dark water, the sounds of the screeches fade away and although it looked quite calm from above, the water starts rushing you rapidly in an unknown direction. The rapids tumble you violently as you struggle to gasp for air. All of a sudden the rapids stop, and almost like it had a life of it\’s own, it pushes you out onto a nearby landing. Coughing and sputtering, you stand on your feet and survey your surroundings. In the distance you spot a castle which you hope might offer a pathway to a portal.','Head towards the castle',NULL,NULL,17,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('the gnarled forest','When you come to, you awaken to a very strange environment. The entire area is awash with white and what looks like dead trees as far as the eye can see. In front of you, some slimy, bulbous figure sits in lurch. This might be the end.','Strike the creature','Run away',NULL,9,29,NULL,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('dreamland mountains','Under development.');
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('a darkly lit cavern',E'“Light!” The room illuminates and it reveals a restorative FLASK potion tucked away in the corner. Let\’s save this for later! The ladder looks like a safe path but there\’s also a hidden hatch nearby leading lower underground.','Climb up the ladder, above the hatch','Lift up the hidden hatch and head down',NULL,56,42,NULL,NULL,1);
INSERT INTO locations (name, plot) VALUES('articulations','Under development.');
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('samurai',E'Along the way to the castle, two samurai are posted. It seems an interaction cannot be avoided. As you approach the samurai, one of them moves forward poses a question: "Why did you decide to a build a game for your 2nd project, when you could have opted for something more innovative or with better utility?" You are confused. It doesn\’t seem like this question is for you.','Answer: "Just because!"',E'Don\’t answer','Crouch and sneak past',31,11,54,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('you died','Under development.'),('render dojo','Under development.');
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('Elson Train escape',E'As the crowd clambers onto the carriage, you follow suit, praying that it will take you to some far away place. After minutes pass, the mechanism of the doors come to life and stutter to slide shut the entrance of the carriage. A soft whirring fills the air and the Elson Train jettisons upwards, before shooting off into the horizon, leaving the station and it\’s commuters lightyears in it\’s rearview.','GAME','OVER','You win!',NULL,NULL,NULL,NULL,NULL);

INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('massive reservoir','At the exit of the tunnel, reaching a massive reservoir, you wonder how big this cavern is. Before you can finish your thought, a swam of seven or eight bat-like creatures at the size of adult humans descends upon your location with shrill screeches.','Jump into the water','Run away',NULL,12,71,NULL,NULL,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('a darkly lit cavern','As you motion for the doorknob, it falls out onto the cavern floor. There is light peaking through the hole in the door.','Peer into the door hole','Back away and examine your surroundings',NULL,48,28,NULL,NULL,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('secret fields','You move toward the left of the field, careful to avoid making noise. As you near the structures, a loud screech fills the field and the dark figures start to move toward you. Dashing past the first few, the fourth catches you off guard and manages to slash against your back. (-10HP) As you fall forward, you spin around and kick off against the next figure, allowing you to launch off into the opposite direction. With a bit of distance between you and your foe, you run. Being outnumbered will not guarantee victory.','Keep running',NULL,NULL,NULL,NULL,NULL,10,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('right tunnel','A cool breeze means there may be a body of water nearby! You follow the tunnel path onwards for what seems like hours until you finally reach the tunnel exit.','Exit the tunnel',NULL,NULL,21,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('you died','Under development.');
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('edge of the badlands','You stay still knowing any movement could aggravate the arachnid. It clicks furiously and takes several steps back. Suddenly the clicking stops, and you slowly move to see that the arachnid is docile and decidedly heading off in the other direction. As you step towards the same direction, you feel a veil is lifted and any tension you could feel previously, now subsides. This feeling is evidence that you have escaped the badlands.','GAME','OVER','You win!',NULL,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('biomechanical heliocore','Under development.');
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('a darkly lit cavern','Peering around you see a ladder leading up to a hatch. It looks like it can be opened.','Climb up the ladder and above the hatch',E'Let\’s cast "Light"! (5 MP)',NULL,56,15,NULL,5,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('you died','You turn to run but feel an incredible pressure on your limbs. As you look down, the dead tree seems to have constricted your body. As you are slowly crushed, you start to wonder if that bulbous figure was another daring traveler who made the same mistake.','GAME','OVER','You lose.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('you died','Under development.');

INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('you died','"INSOLENCE", the samurai yell in unison. They both assume form and strike at your head in tandem.','GAME','OVER','You lose.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('you died','Under development.');
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('blocked entrance','As you swim right around the bubbling, it explodes and the force sends you flying towards the edge of the lake. (-5HP) As you recover, you wipe the lake muck off your body and see that the entrance to the castle is blocked by a towering knight, holding a halberd. Alternatively, you could head towards the airship.','Interact with the knight','Head for the airship',NULL,3,61,NULL,5,NULL);
INSERT INTO locations (name, plot) VALUES('teahouse','Under development.');
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('you died','"Portals seem very effective", you think to yourself as you step into the colourful miasma. You wait to be transported to another area but nothing happens. When you look down at your body, you see that it is all turning to rainbow vapour while the wind gently spreads your remains across the melting forest.','GAME','OVER','You lose.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('path of levitating stone','Under development.'),('you died','Under development.'),('hydras den','Under development.');
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('you died','You stand your ground, ready for what may come. Unfortunately, ready, you were not. The brute force of a dark, nebulous 4-legged creature tears through your body and leaves you lifeless.','GAME','OVER','You lose.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('forgotten library','Under development.');

INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('you died',E'Sadly, it isn\’t an illusion. As you try to pull yourself to safety onto the nearest rock, you notice the bottom half of your body is missing, having being swallowed by the lava. Pulling yourself up didn\’t make sense either, as the rest of you melts away in a maelstrom of flame.','GAME','OVER','You lose.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('lower hatch','Under development.');
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('misty lake',E'SPLASH! Although the lake water around you is strangely warm, the muddiness of the water leaves you feeling like if you were to lower your head any further, it would never come up to the surface again. You cautiously wade across the lake, treading through the thick muck. Dead ahead, there is some bubbling and suddenly you feel the weight of your body double. The lake feels like it\’s pulling you in. You need to get out quickly.','Swim straight on','Swim left','Swim right',47,61,33,NULL,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('you died','You try to hold your breath but the poison acts quickly. You begin to foam at the mouth as your face turns silverish blue from the effects of this unknown toxin.','GAME','OVER','You lose.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('arachnophobia',E'Portals are untrustworthy. You head off in the other direction, cautious not to step on anything other than the forest floor. After sometime, you notice the textures under your feet have begun to feel sticky. The reason for this change, appears in front of you in it\’s grotesque glory, as the echoes of it\’s eerie clicking fills of air. You feel like any action you take may spell certain death.','Attack','Run','Do nothing',55,55,26,NULL,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('melting forest',E'Stepping into the portal, you feel the floor vanish beneath your feet. Looking at the floor, a multitude of colors swirl maniacally until the bright hues darkens to pure black. You realise you\’ve reached the destination. From your view, amidst the muted forest, you can see another colourful portal-like swirl.','Step into colourful portal','Enough portals. Head the other way',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('volcanic maelstrom',E'You swim straight on as it\’s the fastest way out. But as you reach the bubbling, you are you pulled completely under in a blanket of darkness. As you fight against lake, and finally resurface, you realise you\’re no longer in a lake and in the volcanic sea.','It is an illusion','Wake up',NULL,41,41,NULL,NULL,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('bedroom','WHOOSH! Woah, what a weird dream - I should get back to coding...','GAME','OVER','You win!',NULL,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('airship escape',E'The skystream gently lifts you up to the airship deck. A steward greets you and beckons you to take a seat. You\’ve been on an airship before and know that the next destination is always the neighbouring country. You peer down at the badlands hoping to never return.','GAME','OVER','You win!',NULL,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('machine tower','Under development.');

INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('train station',E'Once you enter the portal, you feel your very essence being twisted and turned. This only lasts seconds however, and when the sensations stop, you find yourself the Cloud District. The whirring of steam engines and the blaring of train horns reverberate throughout the station. In your peripheral, you see a crowd hustling toward an Elson Train that\’s due for departure.','Follow the crowd',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('slowdeath','Under development.');
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('sunrise mountain',E'You sprint madly towards the light, hoping that the creature behind is too slow to catch up. You can hear a sharp whistling coupling with small rocks flailing against the tunnel wall, surely as a result of this unknown being giving chase. The orangey glow in your sights soon starts to become a full blown light and once you reach the exit, suddenly the sounds behind you stop. It\’s almost as if it was afraid of the sun. Finally able to catch your breath, you take in the majestic sight as it dawns upon you that it is almost nightfall. You need to get out of here before it\’s too late. The village ahead looks a bit suspicious and is likely a dead-end - it doesn\’t seem like this place offers a friendly respite, after all. On the edge of the village, you spot some fields that look like a way out of the area.','Head to the fields',NULL,NULL,65,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('sleeping fields',E'No need to take chances! Staying at a crouch, you shimmy over to the right and easily pass by unnoticed. When you get far enough away, you stand up and stretch. Suddenly you\’re feeling very sleepy and you notice that it has gotten very dark. Despite your efforts to continue forth, you slowly sink to the floor and lose consciousness.','Zzz...',NULL,NULL,13,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('you died','The second you make a movement, silver threads spool over your limbs. You feel your body lift above the ground and suddenly you spin and spin and spin and spin...','GAME','OVER','You lose.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('upper hatch exit','The ladder is a high climb and as you get closer to the hatch, you can feel the cold rushing towards you. Before you reach the hatch however, the rust of the ladder cuts part of your hand. (-5 HP) As you heave the hatch upward, it reveals another cavernous area with two opposing paths. On the left, you can see a faint glowing warmth and on the right, a cool breeze brushes against your face.','Go left','Go right',NULL,66,24,NULL,5,NULL);
INSERT INTO locations (name, plot) VALUES('shadowlight city','Under development.'),('mystery man','Under development.'),('mystery man','Under development.'),('you win','Under development.');

INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('skystream pathway','As you reach the underside of the airship, you see a skystream - a rush of air that levitates objects in a controlled state. This looks like the only way to get onboard.','Hop into the skystream',NULL,NULL,49,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('you died','Under development.'),('cracked ruins','Under development.');
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('exodimensional room','The knight likes your answer. He steps aside motioning you toward the castle door, which appears to be actually a normal sized house door and happens to slowly creak open. You walk forwards and find yourself in a rather small room that is dwarfed by a portal emitting a bright, fantastical aura. The humming of it draws you near.','Enter the portal','Enter the portal','Enter the portal',46,51,1,NULL,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('secret fields','The walk towards the fields is brief and once you arrive, you are surrounded by a sea of yellow sunhook flowers. In the distance you see strange dark structures, and despite not knowing whether they are living or inanimate, you slowly motion into a crouch. Being too relaxed in an unfamiliar land could get you killed. Over on the far, right there is a clearing and you could easily slip past. The structures on the left are small and could be harmless too. Then again, they could all be inanimate structures despite their shadowy stature.','Head left','Head down the middle','Head right',23,7,54,NULL,NULL);
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('left tunnel',E'You trust the warmth over the cold! You turn left with conviction and start walking towards the orangey glow. From behind, you hear something scratching against the tunnel walls. It seems like something is following you. You\’re not sure what it is but it doesn\’t sound friendly.','Run as fast as you','Stand and fight',NULL,53,39,NULL,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('snowfell paradise','Under development.'),('vulcan provost','Under development.');
INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('lake edge','As you swim left around the bubbling, the lake rage subsides and the consistency of the water seems to return to normal. You make it to the edge of the lake and pull yourself up. Tucked away in a fern, you find a bottle of "Python". You store it in your bag.','Head for the airship',NULL,NULL,61,NULL,NULL,NULL,5);
INSERT INTO locations (name, plot) VALUES('wispy apothecary','Under development.');

INSERT INTO locations (name, plot, c1, c2, c3, m1, m2, m3, cost, item_id) VALUES('floating chateau','You hate yourself for running away but the odds are stacked against you. As you get further away, so do the screeches and when they are out of earshot, you stop to catch your breath. As you lift your eyes and the mist clears, you are confronted by a lake. On the other side, sits a giant castle and beside it, an airship that rivals it in size. The only way across is to swim, it seems.','Jump into the lake',NULL,NULL,43,NULL,NULL,NULL,NULL);
INSERT INTO locations (name, plot) VALUES('you died','Under development.'),('portal room','Under development.');


-- INSERT INTO specials (sp_name, sp_atk, mp_val) VALUES ('Phantasy Slash', 70, 20);
-- INSERT INTO specials (sp_name, sp_atk, mp_val) VALUES ('Slice n Dice', 45, 10);

-- INSERT INTO specials (sp_name, sp_atk, mp_val) VALUES ('Meteoric Break', 120, 50);
-- INSERT INTO specials (sp_name, sp_atk, mp_val) VALUES ('Pyro Flare', 20, 15);

-- INSERT INTO specials (sp_name, sp_atk, mp_val) VALUES ('Breaking n Entering', 60, 30);
-- INSERT INTO specials (sp_name, sp_atk, mp_val) VALUES ('Steal', 40, 10);

-- INSERT INTO specials (sp_name, sp_atk, mp_val) VALUES ('Coin Toss Explosion', 100, 0);
-- INSERT INTO specials (sp_name, sp_atk, mp_val) VALUES ('Rugpull', 10, 0);

INSERT INTO classes (hero_class, hero_atk, hero_hp, hero_mp, item) VALUES ('Knight', 35, 100, 30, 4);
INSERT INTO classes (hero_class, hero_atk, hero_hp, hero_mp, item) VALUES ('Mage', 15, 70, 70, 1);
INSERT INTO classes (hero_class, hero_atk, hero_hp, hero_mp, item) VALUES ('Thief', 25, 100, 40, 5);
INSERT INTO classes (hero_class, hero_atk, hero_hp, hero_mp, item) VALUES ('Lucky Liero', 25, 200, 0, 3);

-- INSERT INTO heroes (hero_id, hero_class, hero_atk, hero_hp, hero_mp, location_id) VALUES (1, 'King Knight', 100, 100, 100, 1)